stages:
  - test
  - deploy

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

.prepare:
  stage: .prepare
  image: python:latest
  cache:
    paths:
      - env/
  before_script:
    - python --version
    - pip --version

test:
  stage: test
  extends: .prepare
  variables:
    INSTANCE: "$INSTANCE"
    TOKEN: "$TOKEN"
  before_script:
    - python -m venv env
    - source env/bin/activate
    - pip install -r requirements.txt
    - pip install .
  script:
    - tox

deploy:
  stage: deploy
  extends: .prepare
  only:
    refs:
      - main
  variables:
    BOM_SERVER: "$BOM_SERVER"
    BOM_KEY: "$BOM_KEY"
    BOM_PROJECT: "$BOM_PROJECT"
  before_script:
    - python -m venv env
    - source env/bin/activate
    - pip install setuptools
    - pip install wheel
    - pip install cyclonedx-bom
    - pip install .
  script:
    - cyclonedx-bom -e -o - > bom.xml
    - curl -X "POST" "$BOM_SERVER" -H "Content-Type:multipart/form-data" -H "X-Api-Key:$BOM_KEY" -F "project=$BOM_PROJECT" -F "bom=@bom.xml"
